### ISSUE TITLE
Feature: A3921の制御方式の変更

### ISSUE THREAD

**Issue by black-c-c** [yutotnh/spirit#37]
**なぜ機能が欲しいのか**
現状HブリッジのHigh側にPWMをかけると波形がおかしくなる為

**提案の説明**
Low側のみにPWMをかける制御に変更

**その他**
制御方式の変更に伴いテストプログラムの内容も変更

**Comment by yutotnh** [comment]
@black-c-c 汎用性を持たせるために、何らかのフラグを用いてHight側, Low側の切り替えを行うように変更できますか?

```C++
// Low側を指定する
A3921.pwm_side(A3921::Side::Low);

// High側を指定する
A3921.pwm_side(A3921::PwmSide::High);
```

**Comment by yutotnh** [comment]
@black-c-c ただ、現状利用しているモータードライバには不具合があるため、デフォルトの設定はLow側でよいと思います。

**Comment by black-c-c** [comment]
@yutotnh デフォルトの設定をLow側に変更するPull Requestを作成しました。

次はHigh sideとLow sideの切り替えを行えるようにします。

**Comment by yutotnh** [comment]
@black-c-c  対応ありがとうございます。
残作業に関して新しいIssueを作成しました。
